default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

primary: &primary
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>

primary_replica: &primary_replica
  <<: *default
  url: <%= ENV['DATABASE_REPLICA_URL'] %>
  replica: true

test_primary: &test_primary
  <<: *default
  url: <%= ENV.fetch("TEST_DATABASE_URL") %>

test_primary_replica: &test_primary_replica
  <<: *default
  url: <%= ENV['TEST_DATABASE_REPLICA_URL'] %>
  replica: true

development:
  primary:
    <<: *primary
  primary_replica:
    <<: *primary_replica

test:
  primary:
    <<: *test_primary
  primary_replica:
    <<: *test_primary_replica

production:
  primary:
    <<: *primary
  primary_replica:
    <<: *primary_replica
